name: Frontend workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      INVENTORY: ${{ secrets.INVENTORY_INI }}
      PEM_KEY: ${{ secrets.SERVER_PEM }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python & Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip git
          pip3 install ansible
          ansible-galaxy collection install community.docker


      - name: Save private key
        run: |
          echo "${PEM_KEY}" > appinstances-kp.pem
          chmod 600 appinstances-kp.pem

      - name: Save inventory
        run: |
          echo "${INVENTORY}" > inventory.ini

      - name: Deploy Frontend
        run: ansible-playbook -i inventory.ini deploy.yaml 
